/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.isu.cs.cs2263.hw02;

public class App{
    public static void main(String args[]){
        MyTokenizer phrase = new MyTokenizer("This is a fancy string with many words.");
        System.out.println(phrase.nextToken());
        System.out.println(phrase.nextToken());
        phrase.pushback();
        System.out.println(phrase.nextToken());
    }
}
